packages:
  - infra/tsconfig-presets
  - infra/dep-presets
  - infra/types
  - packages/monosync
  - packages/ui-web
  - packages/ui-ink
  - packages/signals/core
  - packages/signals/posthog
  - packages/web-global-types
  - packages/utils
  - packages/constants
  - packages/backend/platform
  - packages/backend/utils
  - packages/backend/platform-cloudflare
  - packages/backend/hono

minimumReleaseAge: 1440
blockExoticSubdeps: true
allowBuilds:
  core-js: false
  msw: false
  nx: false
  protobufjs: false
